version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "pip dependencies"
    open-pull-requests-limit: 0   # disable for now
