name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pip dependencies
      run: sudo apt install libxml2-dev libxslt1-dev libpq-dev
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install pip requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install coverage package
      run: pip install coverage
    - name: Run Unit Tests
      run: coverage run -m unittest discover -v -s test/main/
    - name: Upload reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
